version: '3'

services:
  web:
    build: .
    image: ebay_task_web
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    links:
      - redis
    environment:
      - HTTP_PROXY
      - HTTPS_PROXY
  huey:
    image: ebay_task_web
    command: python3 manage.py run_huey -w 2
    environment:
      - HTTP_PROXY
      - HTTPS_PROXY
    volumes:
      - .:/code
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: redis:alpine
