# Generated by Django 2.0.6 on 2018-06-15 02:17

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costumer',
            new_name='Customer',
        ),
    ]
