# Generated by Django 2.0.6 on 2018-06-16 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20180615_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='response',
        ),
        migrations.RemoveField(
            model_name='response',
            name='alert',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
