# Generated by Django 2.0.6 on 2018-06-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20180616_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='updated_minute',
            field=models.IntegerField(default=0),
        ),
    ]
