# Generated by Django 2.0.6 on 2018-06-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alert_updated_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='updated_minute',
            field=models.IntegerField(),
        ),
    ]
